language: python
python:
  - "2.7"
  - "3.5"
# - "nightly" astroid doesn't support 3.6+ yet, causing some tests to fail there.
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
